# Use an existing node alpine image as a base image.
FROM node:18-slim

# Set the working directory.
WORKDIR /app

# Copy the package.json file.
COPY frontend/package.json frontend/yarn.lock ./

# Install application dependencies.
RUN yarn install
 
# Copy the rest of the application files.
COPY ./frontend/ .

# ENV PORT=$PORT
ARG REACT_APP_BACKEND_API_BASE_URL
ARG REACT_APP_BACKEND_API_ADDRESS
ARG REACT_APP_BACKEND_API_PORT
ENV REACT_APP_BACKEND_API_BASE_URL=$REACT_APP_BACKEND_API_BASE_URL
ENV REACT_APP_BACKEND_API_ADDRESS=$REACT_APP_BACKEND_API_ADDRESS
ENV REACT_APP_BACKEND_API_PORT=$REACT_APP_BACKEND_API_PORT

# Expose the port.
EXPOSE $PORT

# Run the application.
CMD yarn start-watch
