services:
  tere-db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
  tere-minio:
    image: 'bitnami/minio:latest'
    container_name: tere_minio
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-tere
      - MINIO_ROOT_PASSWORD=minio-teremere
    volumes:
      - minio_data:/data
  tere-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: tere_api
    env_file:
      - ./.env
    ports:
      - "8000:8080"
    volumes:
      - ./app:/app
    depends_on:
      - tere-db
      - tere-minio
    restart: always
  tere-react:
    build:
      context: .
      dockerfile: ./Dockerfile_frontend_local
    ports:
      - "8080:8080"
      - "3001:3001"
    env_file:
      - ./.app_env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - BACKEND_API_ADDRESS=http://localhost
      - BACKEND_API_PORT=8000
    depends_on:
      - tere-api
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
  tere-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tere@tere.ge
      PGADMIN_DEFAULT_PASSWORD: tere
    depends_on:
      - tere-db
  tere-scheduler:
    build:
      context: .
      dockerfile: ./Dockerfile_scheduler
    volumes:
      - ./scheduler:/app
    env_file:
      - ./.env
    container_name: tere-scheduler
    depends_on:
      - tere-db
      - tere-minio
      - tere-api
    restart: unless-stopped
   

volumes:
  minio_data:
