# Dockerfile

# Use an existing node alpine image as a base image.
FROM node:16

# Set the working directory.
WORKDIR /app

# Copy the package.json file.
COPY frontend/package.json frontend/yarn.lock ./

# Install application dependencies.
RUN yarn install
 
# Copy the rest of the application files.
COPY ./frontend/ .

ENV PORT=3000

# Expose the port.
EXPOSE $PORT

# Run the application.
CMD yarn start
