version: '3.1'

services:
  tere-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: tere_api
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    env_file:
      - ./.env
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    depends_on:
      - tere-mongo
    restart: always
  react-app:
    build:
      context: .
      dockerfile: ./Dockerfile_frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    # REACT_APP_SYNCFUSION_LICENSE_KEY: ${REACT_APP_SYNCFUSION_LICENSE_KEY}
    depends_on:
      - tere-api
    # restart: always
    # volumes:
    #    - ./frontend:/usr/src/app/:delegated
    #    - /usr/src/app/node_modules/
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules

  tere-mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
