# Stage 1: Build the React app
FROM node:18-slim AS build

# Set the working directory
WORKDIR /app

# Copy the package.json and yarn.lock files
COPY frontend/package.json frontend/yarn.lock ./

# Install dependencies
RUN yarn install --frozen-lockfile

# Copy the rest of the application files
COPY ./frontend/ .

# Build the React app
RUN yarn build

# Stage 2: Serve the React app using Nginx
FROM nginx:stable-alpine

# Copy the build output to the Nginx HTML directory
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 8080 for GCP Cloud Run
EXPOSE 8080

# Start Nginx
CMD ["nginx", "-g", "daemon off;"]