version: '3.1'

services:
  tere-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: tere_api
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload
    env_file:
      - ./.env
    ports:
      - "8000:80"
    volumes:
      - ./app:/app
    depends_on:
      - tere-cloudsql-proxy
    restart: always
  tere-react:
    build:
      context: .
      dockerfile: ./Dockerfile_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    # REACT_APP_SYNCFUSION_LICENSE_KEY: ${REACT_APP_SYNCFUSION_LICENSE_KEY}
    depends_on:
      - tere-api
    # restart: always
    # volumes:
    #    - ./frontend:/usr/src/app/:delegated
    #    - /usr/src/app/node_modules/
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
  tere-cloudsql-proxy:
      container_name: tere-cloudsql-proxy
      image: gcr.io/cloudsql-docker/gce-proxy:1.31.1
      command: /cloud_sql_proxy --dir=/cloudsql -instances=tere-421617:europe-north1:tere-db=tcp:0.0.0.0:5432 -credential_file=/secrets/cloudsql/credentials.json -verbose=true
      volumes:
        - ./app/service_account.json:/secrets/cloudsql/credentials.json:ro
      restart: always
  tere-pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: tere@tere.ge
      PGADMIN_DEFAULT_PASSWORD: tere
    depends_on:
      - tere-cloudsql-proxy

# tere-mongo:
#   image: mongo
#   restart: always
#   environment:
#     MONGO_INITDB_ROOT_USERNAME: root
#     MONGO_INITDB_ROOT_PASSWORD: example
# tere-db:
#   image: postgres
#   restart: always
#   # set shared memory limit when using docker-compose
#   shm_size: 128mb
#   environment:
#     POSTGRES_USER: ${DB_USER}
#     POSTGRES_PASSWORD: ${DB_PASSWORD}
#     POSTGRES_DB: ${DB_NAME}
#   ports:
#     - "5432:5432"