import os

DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_HOST = os.getenv('DB_HOST', 'localhost')
DB_PORT = os.getenv('DB_PORT', '5432')
BASE_URL = os.getenv('BASE_URL', '')
API_SECRET_KEY = os.getenv("API_SECRET_KEY")
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("ACCESS_TOKEN_EXPIRE_MINUTES", "30"))
ALGORITHM = "HS256"
INSTANCE_CONNECTION_NAME = os.getenv("INSTANCE_CONNECTION_NAME")
DB_CONNECTION_TYPE = os.getenv("DB_CONNECTION_TYPE", "local")
FRONTEND_APP_ADDRESS = os.getenv("FRONTEND_APP_ADDRESS", "localhost")
FRONTEND_APP_PORT = os.getenv("FRONTEND_APP_PORT")
DOMAIN_NAME = os.getenv("DOMAIN_NAME")